package constants

const (
	APPVIEWX_USERNAME             = "appviewx_username"
	APPVIEWX_PASSWORD             = "appviewx_password"
	APPVIEWX_ENVIRONMENT_Is_HTTPS = "appviewx_environment_is_https"
	APPVIEWX_ENVIRONMENT_IP       = "appviewx_environment_ip"
	APPVIEWX_ENVIRONMENT_PORT     = "appviewx_environment_port"
	APPVIEWX_ACTION_ID            = "action_id"
	MASTER_PAYLOAD                = "master_payload"
	QUERY_PARAMS                  = "query_params"
	DOWNLOAD_FILE_PATH            = "/tmp/"
	DOWNLOAD_FILE_PATH_AUTOMATION = "download_file_path"


	ACCEPT   = "Accept"
	USERNAME = "username"
	PASSWORD = "password"

	HEADERS          = "headers"
	CONTENT_TYPE     = "Content-Type"
	APPLICATION_JSON = "application/json"
	GW_KEY           = "gwkey"
	GW_SOURCE        = "gwsource"
	RESPONSE         = "response"
	SESSION_ID       = "sessionId"
	PAYLOAD          = "payload"
	TYPE             = "type"

	APPVIEWX_ACTION_ID_LOGIN = "login"

	POST   = "POST"
	PUT    = "PUT"
	DELETE = "DELETE"
	GET    = "GET"

	COMMON_NAME                   = "common_name"
	SERIAL_NUMBER                 = "serial_number"
	RESOURCE_ID                   = "resource_id"
	HASH_FUNCTION                 = "hash_function"
	KEY_TYPE                      = "key_type"
	BIT_LENGTH                    = "bit_length"
	DNS_NAMES                     = "dns_names"
	CUSTOM_FIELDS                 = "custom_fields"
	VENDOR_SPECIFIC_FIELDS        = "vendor_specific_fields"
	CERTIFICATE_AUTHORITY         = "certificate_authority"
	CA_SETTING_NAME               = "ca_setting_name"
	VALIDITY                      = "validity_days"
	IS_SYNC                       = "is_sync"
	CERTIFICATE_DOWNLOAD_PATH     = "certificate_download_path"
	CERTIFICATE_DOWNLOAD_FORMAT   = "certificate_download_format"
	CERTIFICATE_DOWNLOAD_PASSWORD = "certificate_download_password"
	CERTIFICATE_CATEGORY          = "certificate_category"
	CERTIFICATE_CHAIN_REQUIRED    = "certificate_chain_required"

	REQUEST_DATA                = "request_data"
	SEQUENCE_NO                 = "sequence_number"
	SCENARIO                    = "scenario"
	FIELD_INFO                  = "field_info"
	EMAIL                       = "email_id"
	TASK_ACTION                 = "task_action"
	HEADER                      = "header"
	WORK_FLOW_NAME              = "work_flow_name"
	INFO                        = "info"
	PUSH_DEVICES                = "push_devices"
	DEVICE_VENDOR               = "device_vendor"
	DEVICE                      = "device"
	LINUX_ACTION                = "linux_actions"
	SELECTED_PROFILES           = "selected_profiles"
	APACHE_CUSTOM_PUSH          = "apache_custom_push"
	APACHE_CERTIFICATE_LOCATION = "apache_certificate_location"
	APACHE_KEY_LOCATION         = "apache_key_location"
)
